config/routes.rb
Grokphoto::Application.routes.draw do

  root :to => "home#welcome"

  match 'timestamp' => 'home#timestamp' # used to keep passenger spooled up in prod
  match 'sitemap' => 'home#sitemap'
  match 'blog' => 'home#blog'
  get '/welcome' => 'home#welcome'
  get '/homepage' => 'home#index'

  resources :private_galleries, :only => :show
  resources :galleries, :only => [:show, :index]
  resources :pages, :only => :show
  resources :posts, :only => [:index, :show]
  resources :contact_requests, :only => [:new, :create] do
    get :thanks, :on => :collection
  end
  resources :service_requests, :only => [:new, :create] do
    get :thanks, :on => :collection
  end

  devise_for :photographers

  match 'admin' => 'admin/events#index'
  namespace :admin do
    resources :events, :only => :index
    resource :photographer, :only => [:edit, :update]
    resources :pages
    resources :posts
    resources :galleries
    resources :private_galleries do
      get :invite, :on => :member
      put :send_invite, :on => :member
    end
    resources :photos, :only => [:edit, :update, :destroy] do
      put 'sort', :on => :collection
    end
  end

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  acts_as_list

  # Associations
  has_many :photos, :as => :photoable, :dependent => :destroy, :order => :position

  # Cover image attachment
  image_accessor :cover

  # Validations
  validates :meta_title, :length => { :within => 2..128, :allow_blank => true }
  validates :keywords, :length => { :within => 2..255, :allow_blank => true }
  validates :meta_description, :length => { :within => 5..255, :allow_blank => true }
  validates :name, :presence => true, :length => { :within => 2..30 }, :uniqueness => { :case_sensitive => false }
  validates :description, :length => { :minimum => 10, :allow_blank => true }
  validates :body, :length => { :minimum => 10, :allow_blank => true }
  validates :cover, :presence => true

  # Mass-assignment protection
  attr_accessible :name, :meta_title, :keywords, :description, :meta_description, :body, :cover, :photos_attrs

  # Multi-file uploads
  def photos_attrs=(attrs)
    attrs.each { |attr| self.photos.build(:photo => attr) }
  end

  # Slug generation
  def to_param
    "#{id}-#{name}".parameterize
  end

  # Default ordering
  default_scope :order => 'position, id'

  # Callbacks
  after_save :clear_cache
  after_create :log_create_event
  after_update :log_update_event
  after_destroy :clear_cache, :log_destroy_event

  # Caching
  CACHED = 'galleries'

  def self.cached
    Rails.cache.fetch(CACHED, :expires_in => 1.day) do
      self.order(:position).all
    end
  end

  def clear_cache
    Gallery.clear_cache
  end

  def self.clear_cache
    Rails.cache.delete(CACHED)
  end

  private #----

    # Logging
    def log_create_event
      Event.create(:description => "Created gallery: #{name}")
    end

    def log_update_event
      Event.create(:description => "Changed gallery: #{name}")
    end

    def log_destroy_event
      Event.create(:description => "Deleted gallery: #{name}")
    end

end

app/controllers/admin/galleries_controller.rb
class Admin::GalleriesController < Admin::HomeController
  respond_to :json, :html
  before_filter :load_resource, :only => [:edit, :update, :destroy]

  def index
    @galleries = Gallery.order(:name)
    respond_with :admin, @galleries
  end

  def new
    respond_with( :admin, @gallery = Gallery.new )
  end

  def create
    @gallery = Gallery.create(params[:gallery])
    if @gallery.valid?
      respond_with(@gallery, :location => edit_admin_gallery_path(@gallery))
    else
      respond_with :admin, @gallery
    end
  end

  def edit
    respond_with :admin, @gallery
  end

  def update
    @gallery.update_attributes params[:gallery]
    if @gallery.valid?
      respond_with(@gallery, :location => edit_admin_gallery_path(@gallery))
    else
      respond_with :admin, @gallery
    end
  end

  def destroy
    @gallery.destroy
    respond_with :admin, @gallery
  end

  private #----

    def load_resource
      @gallery = Gallery.find params[:id]
    end

end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  respond_to :html

  def show
    @gallery = Gallery.find(params[:id])
    @meta_title = @gallery.meta_title.blank? ? "#{@gallery.name} | #{photographer.name}" : @gallery.meta_title
    @keywords = @gallery.keywords
    @meta_description = @gallery.meta_description.blank? ? @gallery.description : @gallery.meta_description
    respond_with @gallery
  end

  def index
    @galleries = Gallery.all
    render :all
  end

end

app/views/admin/galleries/_form.html.haml
- content_for :title, "#{controller.action_name.titleize} Gallery"
- content_for :sidebar do
  %p Enter a descriptive name for the gallery. I.e. Newborn
  %p Upload a cover image that will show up as a home page slides.
  %p It's advisable that you fill out keywords and description with relevant content in order to list higher for related terms in search engines.
  %p Finally, upload the photos that best showcase your work. We recommend limiting the number of photos in a gallery to around 12 or less, otherwise you risk overwhelming potential customers.
  %p When adding photos you can select more than one at a time by holding down your shift or control / command key and selecting photos.

= render "shared/error_messages", :target => @gallery

= form.input :name, :hint => 'Give your private gallery a meaningful name. Like "Jim\'s Wedding"'
= form.input :cover, :as => :file, :label => 'Cover photo', :hint => 'Upload a cover image.'
= form.hidden_field :retained_cover
= link_to( image_tag(@gallery.cover.thumb('180x100').url), @gallery.cover.url, :rel => 'lightbox' ) if @gallery.cover_uid
= form.input :description, :hint => 'Brief description of the gallery for the splash page.'
= form.input :body, :hint => 'Full description of the gallery to appear beneath the photos (SEO). You may use markdown.'
= form.input 'photos_attrs', :label => 'Upload photos', :as => :file, :input_html => { :multiple => true }, :hint => 'Upload many photos by using your shift and control keys.'

= render :partial => "admin/shared/seo_fields", :locals => { :form => form }

.form-actions
  = form.button :submit, :class => 'btn btn-primary'

app/views/admin/galleries/edit.html.haml
- content_for :meta do
  %meta{ :name => "sortable_path", :content => sort_admin_photos_path(:gallery_id => @gallery.to_param) }

= simple_form_for(@gallery, :url => admin_gallery_path(@gallery), :method => :put, :html => { :class => 'form-vertical' }) do |form|
  = render form

%div{ :style => "width:100%; float:left;" }
  %br
  %ul.image_list#sorted-image-list
    = render :partial => "admin/photos/photo", :collection => @gallery.photos

app/views/admin/galleries/index.html.haml
- content_for :title do
  Galleries

%p= link_to(raw("<i class='icon-plus icon-white'></i> New Gallery"), new_admin_gallery_path, :class => 'btn btn-success')

%table.table.table-bordered.table-striped
  %thead
    %tr
      %th Name
      %th Photos
      %th Created on
      %th{ :colspan => 3, :width => '15%' } Actions
  %tbody
    - @galleries.each do |obj|
      %tr
        %td= "#{obj.position}. #{obj.name}"
        %td= obj.photos.size
        %td= obj.created_at.strftime("%b %d, %Y")
        %td= link_to('View', gallery_path(obj))
        %td= link_to('Edit', edit_admin_gallery_path(obj))
        %td= link_to('Delete', admin_gallery_path(obj), :method => :delete, :confirm => 'Are you sure?', :remote => true, 'data-type' => 'json')

app/views/admin/galleries/new.html.haml
= simple_form_for(@gallery, :url => admin_galleries_path, :html => { :class => 'form-vertical' }) do |form|
  = render form