config/routes.rb
Grokphoto::Application.routes.draw do

  root :to => "home#welcome"

  match 'timestamp' => 'home#timestamp' # used to keep passenger spooled up in prod
  match 'sitemap' => 'home#sitemap'
  match 'blog' => 'home#blog'
  get '/welcome' => 'home#welcome'
  get '/homepage' => 'home#index'

  resources :private_galleries, :only => :show
  resources :galleries, :only => [:show, :index]
  resources :pages, :only => :show
  resources :posts, :only => [:index, :show]
  resources :contact_requests, :only => [:new, :create] do
    get :thanks, :on => :collection
  end
  resources :service_requests, :only => [:new, :create] do
    get :thanks, :on => :collection
  end

  devise_for :photographers

  match 'admin' => 'admin/events#index'
  namespace :admin do
    resources :events, :only => :index
    resource :photographer, :only => [:edit, :update]
    resources :pages
    resources :posts
    resources :galleries
    resources :private_galleries do
      get :invite, :on => :member
      put :send_invite, :on => :member
    end
    resources :photos, :only => [:edit, :update, :destroy] do
      put 'sort', :on => :collection
    end
  end

end

app/views/shared/_affiliates-widget.html.erb
<div class="affiliates-container">

  <div class="row affiliates" id="affiliates-1">
    <div class="span3 affiliate">
  <%= image_tag("/assets/affiliates/mcdaniel.png", width: "200", id: "mcdaniel") %>
    </div>
    <div class="span3 affiliate">
  <%= image_tag("/assets/affiliates/cadillac-ranch.png", width: "150", id: "cadillac-ranch") %>
    </div>
    <div class="span3 affiliate">
  <%= image_tag("/assets/affiliates/poorboys.png", width: "150", id: "poorboys") %>
    </div>
    <div class="span3 affiliate">
  <%= image_tag("/assets/affiliates/clocklogo.png", width: "100", id: "clocklogo") %>
    </div>
  </div>

  <div class="row affiliates" id="affiliates-2">
    <div class="span3 affiliate">
  <%= image_tag("/assets/affiliates/pulse.png", width: "200", id: "pulse") %>
    </div>
    <div class="span3 affiliate">
  <%= image_tag("/assets/affiliates/monsto.png", width: "150", id: "monsto") %>
    </div>
    <div class="span3 affiliate">
  <%= image_tag("/assets/affiliates/shadow2.png", width: "200", id: "shadowroom") %>
    </div>
    <div class="span3 affiliate">
  <%= image_tag("/assets/affiliates/stateline.jpeg", width: "200", id: "stateline") %>
    </div>
  </div>

</div>

app/views/shared/_backstretch_carousel.html.erb
<div id="slider-bs">

</div>

<script>
$(document).ready(function(){

  $("#slider-bs").backstretch(["assets/penny.jpg","assets/fox.jpg","assets/car.jpg"], {duration: 3000, fade: 750});

});
</script>

app/views/shared/_disqus.html.haml
#disqus_thread
:javascript
  var disqus_shortname = '#{photographer.disqus_short_name}';

  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function() {
    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();

%noscript
  Please enable JavaScript to view the 
  %a{ href: "http://disqus.com/?ref_noscript" } comments powered by Disqus.
%a.dsq-brlink{ href: "http://disqus.com" }
  comments powered by 
  %span.logo-disqus Disqus

app/views/shared/_error_messages.html.haml
- if target.errors.any?
  #errorExplanation
    %h2
      = pluralize(target.errors.count, "error")
      prohibited this record from being saved:
    %ul
      - target.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="span12" id="foot-content">
        <div class="row">
          <div class="col-xs-2">
            <h4>Photo Galleries</h4>
            <ul class="unstyled">
              <% galleries.each do |gallery| %>
              <li>
                <%= link_to(truncate(gallery.name, :length => 32), gallery_url(gallery)) %>
              </li>
              <% end %>
            </ul>
          </div>
          <div class="col-xs-2">
            <h4>Company Info</h4>
            <ul class="unstyled">
              <% pages.each do |page| %>
              <li>
                <%= link_to(truncate(page.name, :length => 32), page_url(page)) %>
              </li>
              <% end %>
              <li>
                <%= link_to('Contact', new_contact_request_url) %>
              </li>
            </ul>
          </div>
          <div class="col-xs-3">
            <% if photographer.blog_url.blank? %>
            <h4>Recent Posts</h4>
            <ul class="unstyled">
              <% recent_posts.each do |post| %>
              <li>
                <%= link_to(truncate(post.title, :length => 32), post_url(post)) %>
              </li>
              <% end %>
            </ul>
            <% end %>
          </div>
          <div class="col-xs-5 pull-right" id="tagline-column">
            <div id="contact-info">
              <p>
                <% unless photographer.phone.blank? %>
                <strong>Phone</strong>: <%= photographer.phone %>
                <% end %>
              </p>
              <p>
                <strong>Email:</strong> <%= mail_to(photographer.email, photographer.email, :encode => 'javascript').html_safe %>
              </p>
            </div>
            <div id="tagline-info">
              <p>
                <%= photographer.description %>
                <%= render partial: "shared/social"%>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="footer-floor">
    <div class="container">
      <div class="row" id="foot-sole">

        <div class="col-xs-12">
          <%= "&copy; #{Time.now.year} #{photographer.name} All Rights Reserved".html_safe %>
          Website Development by <a href="http://www.ryanskelley.com">Ryan Kelley</a>
          <% unless photographer.phone.blank? %>
          <%= link_to(photographer.phone, "tel:#{photographer.phone}") %>
          <% end %>
          <%= mail_to(photographer.email, photographer.email, :encode => 'javascript').html_safe %>

        </div>

      </div>
    </div>
  </div>
</footer>
<% unless photographer.google_analytics_key.blank? %>
<%= render :partial => 'shared/google_analytics', :locals => { :key => photographer.google_analytics_key } %>
<% end %>

app/views/shared/_footer.html.haml
%footer
  .container
    .row
      .span12
        .row
          .span2
            %h4 Photo Galleries
            %ul.unstyled
              - galleries.each do |gallery|
                %li= link_to(truncate(gallery.name, :length => 32), gallery_url(gallery))
          .span2
            %h4 Company Info
            %ul.unstyled
              - pages.each do |page|
                %li= link_to(truncate(page.name, :length => 32), page_url(page))
              %li= link_to('Contact', new_contact_request_url)
          .span3
            - if photographer.blog_url.blank?
              %h4 Recent Posts
              %ul.unstyled
                - recent_posts.each do |post|
                  %li= link_to(truncate(post.title, :length => 32), post_url(post))

          .span5.pull-right
            %p= photographer.description
  #footer-floor
    .container
      .row
        .span12
          %h4
            - unless photographer.phone.blank?
              = photographer.phone
              \/
            = mail_to(photographer.email, photographer.email, :encode => 'javascript').html_safe
          %p= "&copy; #{Time.now.year}, #{photographer.name}, All Rights Reserved".html_safe

- unless photographer.google_analytics_key.blank?
  = render :partial => 'shared/google_analytics', :locals => { :key => photographer.google_analytics_key }

app/views/shared/_google_analytics.html.haml
%script{ type: "text/javascript" }
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '#{key}']);
  - if photographer.preferred_domain
    _gaq.push(['_setDomainName', '#{photographer.preferred_domain}']);
  _gaq.push(['_setAllowLinker', true]);
  _gaq.push(['_trackPageview']);

  (function() {
  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/shared/_navbar.html.erb
 <div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <ul class="nav">
        <li class="dropdown">
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">Photo Galleries<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <% galleries.each do |gallery| %>
            <li class=<%= (defined?(@gallery) and @gallery.id == gallery.id ? 'active' : '')%>> <%=link_to(gallery.name,gallery_url(gallery)) %>
            </li>
            <% end %>
            <li>
              <%= link_to("All", '/galleries') %>
            </li>
          </ul>
        </li>
        <% pages.each do |page| %>
        <li class=<%= (defined?(@page) and @page.id == page.id ? 'active' : '')%>> <%= link_to(page.name, page_url(page)) %>
        </li>
        <% end %>
        <li class=<%= controller.controller_name == 'posts' ? 'active' : '' %>> <%= link_to('Blog', photographer.blog_url.blank? ? posts_url : photographer.blog_url) %>
        </li>
        <li class="divider-vertical"></li>
        <li class=<%= controller.controller_name == 'contact_requests' ? 'active' : '' %>> <%= link_to('Contact', new_contact_request_url) %>
        </li>
        <li class=<%= controller.controller_name == 'service_requests' ? 'active' : '' %>> <%= link_to('Request Appointment', new_service_request_url) %>
        </li>
      </ul>
      <div class="pull-right">
        <%= link_to(photographer.name, homepage_path, :class => 'brand') %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_old-front-page-carousel.html.erb
<div class="row">
  <div class="span12 front-carousel-container">
    <div class="carousel" id="carousel">
      <div class="carousel-inner">
        <% galleries.each_with_index do |gallery, idx| %>
        <div class="item<%= ' active' if idx == 0 %>">
          <%= link_to( image_tag(gallery.cover.thumb('940x500!').url), gallery_url(gallery) ) %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_recent-posts-widget.html.erb
<ul class="media-list frontpage">
  <% recent_posts.each do |post| %>
  <li class="media">
    <a class="pull-left" href="#">
     <!--  <img class="media-object" src="assets/car.jpg" width="100"> -->
   <%= image_tag(post.image.thumb('100x100').url, class: "media-object") if post.image_uid %>
    </a>
    <div class="media-body">
      <h2 class="media-heading"><%= link_to(truncate(post.title, length: 32), post_url(post)) %>
      </h2>
      <div class="post-preview">
      <%= truncate(post.body, length: 250) %>
    </div>
    </div>
  </li>
  <% end %>
</ul>

app/views/shared/_small-foot.html.erb
  <div id="footer-floor" class="stick-to-bottom">
    <div class="container">
      <div class="row push-left">
        <h4 id="center-me">
          <% unless photographer.phone.blank? %>
          <%= photographer.phone %>
          |
          <% end %>
          <%= mail_to(photographer.email, photographer.email, class: "welcome-link", :encode => 'javascript').html_safe %>
          |
          <%= "&copy; #{Time.now.year}, #{photographer.name}, All Rights Reserved".html_safe %>
        </h4>
      </div>
    </div>
  </div>

app/views/shared/_social.html.erb
<ul class="rrssb-buttons clearfix">
    <li class="email">
        <a href="mailto:?subject=Check%20out%20how%20ridiculously%20responsive%20these%20social%20buttons%20are&amp;body=http%3A%2F%2Fkurtnoble.com%2Flabs%2Frrssb%2Findex.html">
            <span class="icon">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" x="0px" y="0px" width="28px" height="28px" viewBox="0 0 28 28" enable-background="new 0 0 28 28" xml:space="preserve"><g><path d="M20.111 26.147c-2.336 1.051-4.361 1.401-7.125 1.401c-6.462 0-12.146-4.633-12.146-12.265 c0-7.94 5.762-14.833 14.561-14.833c6.853 0 11.8 4.7 11.8 11.252c0 5.684-3.194 9.265-7.399 9.3 c-1.829 0-3.153-0.934-3.347-2.997h-0.077c-1.208 1.986-2.96 2.997-5.023 2.997c-2.532 0-4.361-1.868-4.361-5.062 c0-4.749 3.504-9.071 9.111-9.071c1.713 0 3.7 0.4 4.6 0.973l-1.169 7.203c-0.388 2.298-0.116 3.3 1 3.4 c1.673 0 3.773-2.102 3.773-6.58c0-5.061-3.27-8.994-9.303-8.994c-5.957 0-11.175 4.673-11.175 12.1 c0 6.5 4.2 10.2 10 10.201c1.986 0 4.089-0.43 5.646-1.245L20.111 26.147z M16.646 10.1 c-0.311-0.078-0.701-0.155-1.207-0.155c-2.571 0-4.595 2.53-4.595 5.529c0 1.5 0.7 2.4 1.9 2.4 c1.441 0 2.959-1.828 3.311-4.087L16.646 10.068z"/></g></svg>
            </span>
            <span class="text">email</span>
        </a>
    </li>
    <li class="facebook">
        <a href="https://www.facebook.com/sharer/sharer.php?u=http://shprophoto.com" class="popup">
            <span class="icon">
                <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="28px" height="28px" viewBox="0 0 28 28" enable-background="new 0 0 28 28" xml:space="preserve">
                    <path d="M27.825,4.783c0-2.427-2.182-4.608-4.608-4.608H4.783c-2.422,0-4.608,2.182-4.608,4.608v18.434
                        c0,2.427,2.181,4.608,4.608,4.608H14V17.379h-3.379v-4.608H14v-1.795c0-3.089,2.335-5.885,5.192-5.885h3.718v4.608h-3.726
                        c-0.408,0-0.884,0.492-0.884,1.236v1.836h4.609v4.608h-4.609v10.446h4.916c2.422,0,4.608-2.188,4.608-4.608V4.783z"/>
                </svg>
            </span>
            <span class="text">facebook</span>
        </a>
    </li>
    <li class="twitter">
        <a href="http://twitter.com/home?status=Stephen%20Hirschthal%20Photography%20is%20top%20notch!%20www.shprophoto.com" class="popup">
            <span class="icon">
                <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                     width="28px" height="28px" viewBox="0 0 28 28" enable-background="new 0 0 28 28" xml:space="preserve">
                <path d="M24.253,8.756C24.689,17.08,18.297,24.182,9.97,24.62c-3.122,0.162-6.219-0.646-8.861-2.32
                    c2.703,0.179,5.376-0.648,7.508-2.321c-2.072-0.247-3.818-1.661-4.489-3.638c0.801,0.128,1.62,0.076,2.399-0.155
                    C4.045,15.72,2.215,13.6,2.115,11.077c0.688,0.275,1.426,0.407,2.168,0.386c-2.135-1.65-2.729-4.621-1.394-6.965
                    C5.575,7.816,9.54,9.84,13.803,10.071c-0.842-2.739,0.694-5.64,3.434-6.482c2.018-0.623,4.212,0.044,5.546,1.683
                    c1.186-0.213,2.318-0.662,3.329-1.317c-0.385,1.256-1.247,2.312-2.399,2.942c1.048-0.106,2.069-0.394,3.019-0.851
                    C26.275,7.229,25.39,8.196,24.253,8.756z"/>
                </svg>
            </span>
            <span class="text">twitter</span>
        </a>
    </li>
      <li class="googleplus">
                        <!-- Replace href with your meta and URL information.  -->
                        <a href="https://plus.google.com/share?url=Stephen%20Hirschthal%20Photography%20is%20top%20notch!%20http://shprophoto.com" class="popup">
                            <span class="icon">
                                <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="28px" height="28px" viewBox="0 0 28 28" enable-background="new 0 0 28 28" xml:space="preserve">
                                    <g>
                                        <g>
                                            <path d="M14.703,15.854l-1.219-0.948c-0.372-0.308-0.88-0.715-0.88-1.459c0-0.748,0.508-1.223,0.95-1.663
                                                c1.42-1.119,2.839-2.309,2.839-4.817c0-2.58-1.621-3.937-2.399-4.581h2.097l2.202-1.383h-6.67c-1.83,0-4.467,0.433-6.398,2.027
                                                C3.768,4.287,3.059,6.018,3.059,7.576c0,2.634,2.022,5.328,5.604,5.328c0.339,0,0.71-0.033,1.083-0.068
                                                c-0.167,0.408-0.336,0.748-0.336,1.324c0,1.04,0.551,1.685,1.011,2.297c-1.524,0.104-4.37,0.273-6.467,1.562
                                                c-1.998,1.188-2.605,2.916-2.605,4.137c0,2.512,2.358,4.84,7.289,4.84c5.822,0,8.904-3.223,8.904-6.41
                                                c0.008-2.327-1.359-3.489-2.829-4.731H14.703z M10.269,11.951c-2.912,0-4.231-3.765-4.231-6.037c0-0.884,0.168-1.797,0.744-2.511
                                                c0.543-0.679,1.489-1.12,2.372-1.12c2.807,0,4.256,3.798,4.256,6.242c0,0.612-0.067,1.694-0.845,2.478
                                                c-0.537,0.55-1.438,0.948-2.295,0.951V11.951z M10.302,25.609c-3.621,0-5.957-1.732-5.957-4.142c0-2.408,2.165-3.223,2.911-3.492
                                                c1.421-0.479,3.25-0.545,3.555-0.545c0.338,0,0.52,0,0.766,0.034c2.574,1.838,3.706,2.757,3.706,4.479
                                                c-0.002,2.073-1.736,3.665-4.982,3.649L10.302,25.609z"/>
                                            <polygon points="23.254,11.89 23.254,8.521 21.569,8.521 21.569,11.89 18.202,11.89 18.202,13.604 21.569,13.604 21.569,17.004
                                                23.254,17.004 23.254,13.604 26.653,13.604 26.653,11.89      "/>
                                        </g>
                                    </g>
                                </svg>
                            </span>
                            <span class="text">google+</span>
                        </a>
                    </li>
                    <li class="youtube">
                        <a href="#">
                            <span class="icon">
                                <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="28px" height="28px" viewBox="0 0 28 28" enable-background="new 0 0 28 28" xml:space="preserve">
                                    <path d="M27.688,8.512c0-2.268-1.825-4.093-4.106-4.093H4.389c-2.245,0-4.076,1.825-4.076,4.093v10.976 c0,2.268,1.825,4.093,4.076,4.093h19.192c2.274,0,4.106-1.825,4.106-4.093V8.512z M11.263,18.632V8.321l7.817,5.155L11.263,18.632z" />
                                </svg>
                            </span>
                            <span class="text">youtube</span>
                        </a>
                    </li>
                    <li class="pinterest">
                        <!-- Replace href with your meta and URL information.  -->
                        <a href="http://pinterest.com/pin/create/button/?url=http://kurtnoble.com/labs/rrssb/index.html&amp;media=https://www.flickr.com/photos/8778800@N04/6832079652/&amp;description=tephen%20Hirschthal%20Photography%20is%20top%20notch!%20">
                            <span class="icon">
                                <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="28px" height="28px" viewBox="0 0 28 28" enable-background="new 0 0 28 28" xml:space="preserve">
                                <path d="M14.021,1.57C6.96,1.57,1.236,7.293,1.236,14.355c0,7.062,5.724,12.785,12.785,12.785c7.061,0,12.785-5.725,12.785-12.785
                                    C26.807,7.294,21.082,1.57,14.021,1.57z M15.261,18.655c-1.161-0.09-1.649-0.666-2.559-1.219c-0.501,2.626-1.113,5.145-2.925,6.458
                                    c-0.559-3.971,0.822-6.951,1.462-10.116c-1.093-1.84,0.132-5.545,2.438-4.632c2.837,1.123-2.458,6.842,1.099,7.557
                                    c3.711,0.744,5.227-6.439,2.925-8.775c-3.325-3.374-9.678-0.077-8.897,4.754c0.19,1.178,1.408,1.538,0.489,3.168
                                    C7.165,15.378,6.53,13.7,6.611,11.462c0.131-3.662,3.291-6.227,6.46-6.582c4.007-0.448,7.771,1.474,8.29,5.239
                                    c0.579,4.255-1.816,8.865-6.102,8.533L15.261,18.655z"/>
                                </svg>
                            </span>
                            <span class="text">pinterest</span>
                        </a>
                    </li>

</ul>