config/routes.rb
Grokphoto::Application.routes.draw do

  root :to => "home#welcome"

  match 'timestamp' => 'home#timestamp' # used to keep passenger spooled up in prod
  match 'sitemap' => 'home#sitemap'
  match 'blog' => 'home#blog'
  get '/welcome' => 'home#welcome'
  get '/homepage' => 'home#index'

  resources :private_galleries, :only => :show
  resources :galleries, :only => [:show, :index]
  resources :pages, :only => :show
  resources :posts, :only => [:index, :show]
  resources :contact_requests, :only => [:new, :create] do
    get :thanks, :on => :collection
  end
  resources :service_requests, :only => [:new, :create] do
    get :thanks, :on => :collection
  end

  devise_for :photographers

  match 'admin' => 'admin/events#index'
  namespace :admin do
    resources :events, :only => :index
    resource :photographer, :only => [:edit, :update]
    resources :pages
    resources :posts
    resources :galleries
    resources :private_galleries do
      get :invite, :on => :member
      put :send_invite, :on => :member
    end
    resources :photos, :only => [:edit, :update, :destroy] do
      put 'sort', :on => :collection
    end
  end

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  layout 'admin'
  before_filter :authenticate_photographer!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'splash'

  def timestamp
    render text: Time.zone.now
  end

  def index
    @meta_title = photographer.meta_title.blank? ? photographer.name : photographer.meta_title
    @keywords = photographer.keywords
    @meta_description = photographer.meta_description.blank? ? photographer.description : photographer.meta_description
    @post_ids = Post.latest_post_ids(3)
  end

  def sitemap
    render layout: nil
  end

  def blog
    unless photographer.blog_url.blank?
      redirect_to photographer.blog_url, status: 301
    else
      raise ActionController::RoutingError.new('Not Found')
    end
  end

  def welcome
    @meta_title = photographer.meta_title.blank? ? photographer.name : photographer.meta_title
    @keywords = photographer.keywords
    @meta_description = photographer.meta_description.blank? ? photographer.description : photographer.meta_description
    render template: "home/welcome-page", layout: "layouts/welcome-layout"
  end
end

app/views/home/index.html.erb
<!-- <div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <ul class="nav">
        <% galleries.each do |gallery| %>
        <li class=<%= (defined?(@gallery) and @gallery.id == gallery.id ? 'active' : '') %>> <%= link_to(gallery.name,   gallery_url(gallery)) %>
        </li>
        <% end %>
        <% pages.each do |page| %>
        <li class=<%=(defined?(@page) and @page.id == page.id   ? 'active' : '')%>> <%= link_to(page.name, page_url(page)) %>
        </li>
        <% end %>
        <li class=<%= controller.controller_name == 'posts' ? '  active' : ''%>> <%= link_to('Blog', photographer.blog_url.blank? ? posts_url : photographer.blog_url) %>
        </li>
        <li class="divider-vertical"></li>
        <li class=<%= controller.controller_name == '  contact_requests' ? 'active' : ''%>> <%= link_to('Contact',   new_contact_request_url) %>
        </li>
      </ul>
      <div class="pull-right">
        <%= link_to(photographer.name, root_url, :class => 'brand') %>
      </div>
    </div>
  </div>
</div> -->
<!-- end alternate navbar -->

<%= render :partial => 'shared/navbar' %>


<!-- end dropdown navbar -->

<div id="frontpage-logo-container">
  <%= image_tag("/assets/logos/SHPlogo-1.png", width: "500", id: "frontpage-logo-image") %>
</div>

<div class="jumbotron masthead">
  <div class="inner front-heading">
    <h1>
      <%= photographer.name %>
    </h1>
    <p id="header-tagline">
      <%= photographer.tagline %>
    </p>
  </div>
</div>
<!-- frontpage carousel replaced with backstretch partial -->
<%= render "shared/backstretch_carousel" %>

<hr class="frontpage-rule" id="carousel-rule">

<div class="panel panel-primary" id="portfolio-panel">
  <div class="panel-heading">
    <h1>Portfolio</h1>
  </div>
  <div class="panel-body">
    <div class="marketing">
      <% galleries.each_slice(3) do |galleries| %>
      <div class="row">
        <% galleries.each do |gallery| %>
        <div class="span4">
          <div class="thumbnail">
            <h2 class="gallery-name">
              <%= link_to(gallery.name, gallery_path(gallery), :class => 'marketing-link') %>
            </h2>
            <div class="content">
              <p class="gal-description">
                <%= gallery.description %>
              </p>
              <p class="gal-button-row">
                <%= link_to('View this gallery &raquo;'.html_safe, gallery_url(gallery), :class => 'btn gal-button') %>
              </p>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <% end %>
    </div> <!-- end panel-body -->
  </div> <!-- end panel panel-primary -->
</div>

<hr id="carousel-rule-middle">

<% if photographer.blog_url.blank? %>
<div class="blog-widget-container">
<div class="row">
  <div class="panel-heading add-bottom-border">
    <h1>Blog Posts</h1>
  </div>
<%= render "shared/recent-posts-widget" %>
</div><!-- end row -->
</div> <!-- end blog-widget-container -->
<% end %>
<hr>

<div class="panel-heading add-bottom-border">
    <h1>Happy Customers</h1>
  </div>
<%= render "shared/affiliates-widget" %>

<hr class= "frontpage-rule" id="bottom-rule">

app/views/home/welcome-page.html.erb
<div class="container">

  <div id="welcome-logo-container">
  <%= image_tag("/assets/logos/SHPlogo-1.png", width: "400", id: "frontpage-logo-image") %>
</div>


    <div class="row">
      <div class="col-md-12 text-center">
        <div id="logo" class="welcome-title">Stephen Hirschthal Photography</div>
        <!-- <h1>Professional Photography with an Artistic Touch</h1> -->
      <!--   <h2></h2> -->
      </div> <!-- /.col-md-12 -->
    </div> <!-- /.row -->

    <div class="row">
      <div id="welcome-button-div" class="col-md-12 text-center">
        <form class="form-inline" role="form" action="/homepage">
          <div class="form-group">
          <button id="welcome-enter" type="submit" class="btn btn-primary">Click to Enter</button>
        </form>
      </div> <!-- /.col-md-12 -->
    </div> <!-- /.row -->

    <div class="row">
      <div class="col-md-12 text-center" id="links">
        <p>
          <a class="welcome-link" href="http://shprophoto.com">
            <span class="glyphicon glyphicon-home"></span>
            Mainpage
          </a>
          <span class="separator">&middot;</span>
          <a class="welcome-link" href="/pages/1-about-stephen">
            <span class="glyphicon glyphicon-user"></span>
            About Us
          </a>
          <span class="separator">&middot;</span>
          <a class="welcome-link" href="https://www.shprophoto.com/galleries">
            <span class="glyphicon glyphicon-briefcase"></span>
            Portfolio
          </a>
          <span class="separator">&middot;</span>
          <a class="welcome-link" href="http://www.facebook.com/sharer.php?u=http://shprophoto.com/">
            <span class="glyphicon glyphicon-thumbs-up"></span>
            Like Us
          </a>
          <span class="separator">&middot;</span>
          <a class="welcome-link" href="/contact_requests/new">
            <span class="glyphicon glyphicon-envelope"></span>
            Contact Us
          </a>
        </p>
      </div> <!-- #links -->
    </div> <!-- /.row -->

  </div> <!-- /.container -->

      <script src="js/jquery.js"></script>
      <script src="js/bootstrap.min.js"></script>