config/routes.rb
Grokphoto::Application.routes.draw do

  root :to => "home#welcome"

  match 'timestamp' => 'home#timestamp' # used to keep passenger spooled up in prod
  match 'sitemap' => 'home#sitemap'
  match 'blog' => 'home#blog'
  get '/welcome' => 'home#welcome'
  get '/homepage' => 'home#index'

  resources :private_galleries, :only => :show
  resources :galleries, :only => [:show, :index]
  resources :pages, :only => :show
  resources :posts, :only => [:index, :show]
  resources :contact_requests, :only => [:new, :create] do
    get :thanks, :on => :collection
  end
  resources :service_requests, :only => [:new, :create] do
    get :thanks, :on => :collection
  end

  devise_for :photographers

  match 'admin' => 'admin/events#index'
  namespace :admin do
    resources :events, :only => :index
    resource :photographer, :only => [:edit, :update]
    resources :pages
    resources :posts
    resources :galleries
    resources :private_galleries do
      get :invite, :on => :member
      put :send_invite, :on => :member
    end
    resources :photos, :only => [:edit, :update, :destroy] do
      put 'sort', :on => :collection
    end
  end

end

app/models/private_gallery.rb
class PrivateGallery < ActiveRecord::Base

  # Associations
  has_many :photos, :as => :photoable, :dependent => :destroy, :order => :position

  # Virtual attribute for sending email invitations.
  attr_accessor :email

  # Validations
  validates :name, :presence => true, :length => { :within => 2..100 }
  validates :email, :length => { :within => 5..128, :allow_blank => true }

  # Mass-assignment protection
  attr_accessible :name, :email, :expires_on, :photos_attrs

  # Named scopes
  scope :active, where("expires_on >= ?", Time.now)
  scope :expired, where("expires_on < ?", Time.now)

  # Multi-file uploads
  def photos_attrs=(attrs)
    attrs.each { |attr| self.photos.build(:photo => attr) }
  end

  # Determine if the private gallery has expired.
  def expired?
    (self.expires_on and self.expires_on < Date.today) || false
  end

  # Callbacks
  before_create :build_token
  after_create :log_create_event
  after_update :log_update_event
  after_destroy :log_destroy_event

  private #----

    # Secures private galleries by using an unguessable token.
    def build_token
      self.token = Devise.friendly_token
    end

    def log_create_event
      Event.create(:description => "Created private gallery: #{name}")
    end

    def log_update_event
      Event.create(:description => "Changed private gallery: #{name}")
    end

    def log_destroy_event
      Event.create(:description => "Deleted private gallery: #{name}")
    end

end

app/controllers/admin/private_galleries_controller.rb
class Admin::PrivateGalleriesController < Admin::HomeController
  respond_to :json, :html
  before_filter :load_resource, :only => [:edit, :update, :destroy, :invite, :send_invite]

  def index
    params[:order] = 'name' unless params[:order]
    @private_galleries = PrivateGallery.order(params[:order])

    if defined?(params[:search][:q]) and params[:search][:q]
      term = Regexp.escape(params[:search][:q])
      @private_galleries = @private_galleries.where(["name ~* ?", term])
    end

    @private_galleries = @private_galleries.page(params[:page])
    respond_with :admin, @private_galleries
  end

  def new
    @private_gallery = PrivateGallery.new
    @private_gallery.expires_on = 4.weeks.from_now
    respond_with :admin, @private_gallery
  end

  def create
    @private_gallery = PrivateGallery.create(params[:private_gallery])
    if @private_gallery.valid?
      respond_with(@private_gallery, :location => edit_admin_private_gallery_path(@private_gallery))
    else
      respond_with :admin, @private_gallery
    end
  end

  def edit
    respond_with :admin, @private_gallery
  end

  def update
    @private_gallery.update_attributes params[:private_gallery]
    if @private_gallery.valid?
      respond_with(@private_gallery, :location => edit_admin_private_gallery_path(@private_gallery))
    else
      respond_with :admin, @private_gallery
    end
  end

  def destroy
    @private_gallery.destroy
    respond_with :admin, @private_gallery
  end

  def invite
  end

  def send_invite
    # Send the email
    begin
      PrivateGalleryMailer.invite(photographer.email, params[:private_gallery][:email], @private_gallery).deliver

      redirect_to admin_private_galleries_path, :notice => 'Private gallery sent.'
    rescue Exception => e
      render :invite, :error => 'The was a problem sending an email to the address you provided.'
    end
  end

  private #----

    def load_resource
      @private_gallery = PrivateGallery.find params[:id]
    end

end

app/controllers/private_galleries_controller.rb
class PrivateGalleriesController < ApplicationController
  respond_to :html

  def show
    @photographer = Photographer.first
    @private_gallery = PrivateGallery.find_by_token(params[:id])
    if @private_gallery
      @meta_title = @private_gallery.name
      render
    else
      redirect_to(root_path, :alert => "Unable to find that private gallery.")
    end
  end

end

app/views/admin/private_galleries/_form.html.haml
- content_for :title, "#{controller.action_name.titleize} Private Gallery"
- content_for :sidebar do
  %p Enter a descriptive name for the private gallery. I.e. Newborn Session
  %p The "Expires on" field limits how long the client can view this private gallery and the photos within it.
  %p When adding photos you can select more than one at a time by holding down your shift or control / command key and selecting photos.

= render "shared/error_messages", :target => @private_gallery

= form.input :name, :hint => 'Give your private gallery a meaningful name. Like "Jim\'s Wedding"'
= form.input :expires_on, :as => :string, :input_html => { :class => 'date_picker', :value => @private_gallery.expires_on.strftime('%B %d, %Y') }, :hint => 'Select the date when the gallery should expire.'
= form.input 'photos_attrs', :label => 'Upload Photos', :as => :file, :input_html => { :multiple => true }, :hint => 'Upload multiple photos at once by using your shift or control / command keys.'

.form-actions
  = form.button :submit, :class => 'btn btn-primary'

app/views/admin/private_galleries/edit.html.haml
= simple_form_for(@private_gallery, :url => admin_private_gallery_path, :method => :put, :html => { :class => 'form-vertical' }) do |form|
  = render form

%div{ :style => "width:100%; float:left;" }
  %br
  %ul.image_list
    = render :partial => "admin/photos/photo", :collection => @private_gallery.photos

app/views/admin/private_galleries/index.html.haml
- content_for :title do
  Private Galleries
  .pull-right
    = form_for :search, :url => admin_private_galleries_path, :method => :get, :class => 'form-search' do |form|
      = form.text_field :q, :placeholder => 'Search', :class => 'input-medium search-query', :value => defined?(params[:search][:q]) ? params[:search][:q] : ''

%p= link_to(raw("<i class='icon-plus icon-white'></i> New Private Gallery"), new_admin_private_gallery_path, :class => 'btn btn-success')

%table.table.table-bordered.table-striped
  %thead
    %tr
      %th Name
      %th Photos
      %th Created on
      %th Expires on
      %th{ :colspan => 4, :width => '20%' } Actions
  %tbody
    - @private_galleries.each do |obj|
      %tr
        %td= obj.name
        %td= obj.photos.size
        %td= obj.created_at.strftime("%b %d, %Y")
        %td= obj.expires_on > Time.zone.now ? obj.expires_on.strftime("%b %d, %Y") : 'Expired'
        %td= link_to('View', private_gallery_path(obj.token))
        %td= link_to('Invite', invite_admin_private_gallery_path(obj))
        %td= link_to('Edit', edit_admin_private_gallery_path(obj))
        %td= link_to('Delete', admin_private_gallery_path(obj), :method => :delete, :confirm => 'Are you sure?', :remote => true, 'data-type' => 'json')

= paginate @private_galleries

app/views/admin/private_galleries/invite.html.haml
- content_for :title, "#{controller.action_name.titleize} to Private Gallery"
- content_for :sidebar do
  %p Enter the email address of your client and we'll send them instructions with a secure link for viewing their private gallery.

= simple_form_for(@private_gallery, :url => send_invite_admin_private_gallery_path(@private_gallery), :method => :put, :html => { :class => 'form-vertical' }) do |form|
  = form.input :email, :hint => 'Enter the email address of your client.'

  .form-actions
    = form.button :submit, 'Send Private Gallery', :class => 'btn-primary'
    &nbsp;
    = link_to('Cancel', admin_private_galleries_path, :class => 'btn')

app/views/admin/private_galleries/new.html.haml
= simple_form_for(@private_gallery, :url => admin_private_galleries_path, :html => { :class => 'form-vertical' }) do |form|
  = render form